files:
  - source: README.md
    translation: /resources/readme/%locale_with_underscore%.md
  - source: /resources/languages/expanded/en_us.json
    translation: /resources/languages/expanded/%locale_with_underscore%.json
