version: '3.5'
services:
  mc-linker:
    image: lianecx/${SERVICE_NAME}
    container_name: ${SERVICE_NAME}
    restart: on-failure
    ports:
      - "${BOT_PORT}:${BOT_PORT}"
    volumes:
      - type: bind
        source: ./download-cache
        target: /usr/src/app/download-cache
    environment:
      - DEBUG=$DEBUG
      - CONVERT=$CONVERT # true or false
    networks:
      - mongo-network

  mongodb:
    image: mongo
    container_name: mongodb
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./mongodb
        target: /data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongodb
    networks:
      - mongo-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - '8081:8081'
    volumes:
      - ./data:/data/db

networks:
  mongo-network:
    driver: bridge
