version: '3.5'
services:
  mc-linker:
    image: lianecx/mc-linker
    container_name: mc-linker
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - "${BOT_PORT}:${BOT_PORT}"
    volumes:
      - type: bind
        source: ./download-cache
        target: /usr/src/app/download-cache
      - type: bind
        source: ./logs
        target: /usr/src/app/logs
      - type: bind
        source: ./Custom-MC-Linker
        target: /usr/src/Custom-MC-Linker
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - CONVERT=$CONVERT # true or false
      - DATA_FOLDER=./
      - NODE_ENV=production
      - NODE_MAX_HEAP_SIZE=8192
    networks:
      - mongo-network

  mongodb:
    image: mongo
    container_name: mongodb
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./mongodb
        target: /data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongodb
    networks:
      - mongo-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    ports:
      - '8081:8081'
    volumes:
      - ./data:/data/db

networks:
  mongo-network:
    driver: bridge
