services:
  mc-linker:
    image: lianecx/${SERVICE_NAME}
    container_name: ${SERVICE_NAME}
    restart: on-failure
    ports:
      - "${BOT_PORT}:${BOT_PORT}"
    volumes:
      - type: bind
        source: ./download-cache
        target: /usr/src/app/download-cache
      - type: bind
        source: ./logs
        target: /usr/src/app/logs
      - type: bind
        source: ./Custom-MC-Linker
        target: /usr/src/app/Custom-MC-Linker
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=$LOG_LEVEL
      - CONVERT=$CONVERT # true or false
      - NODE_MAX_HEAP_SIZE=1024
    networks:
      - mc-linker_mongo-network

networks:
  mc-linker_mongo-network:
    external: true
