export default {
    ServerConnection: {
        _id: { type: String },
        ip: String,
        version: Number,
        path: String,
        worldPath: String,
        online: Boolean,
        forceOnlineMode: Boolean,
        floodgatePrefix: String,
        requiredRoleToJoin: { method: { type: String, enum: ['all', 'any'] }, roles: [String] },
        displayIp: String,
        port: Number,
        hash: String,
        chatChannels: [{
            _id: { type: String },
            types: [{
                type: String,
                enum: ['chat', 'console', 'join', 'quit', 'advancement', 'death', 'player_command', 'console_command', 'block_command', 'start', 'close'],
            }],
            allowDiscordToMinecraft: Boolean,
            webhooks: [String],
        }],
        statChannels: [{
            _id: { type: String },
            type: { type: String, enum: ['member-counter', 'status'] },
            names: {
                online: String,
                offline: String,
                members: String,
            },
        }],
        syncedRoles: [{
            _id: { type: String },
            name: String,
            isGroup: Boolean,
            players: [String],
            direction: { type: String, enum: ['both', 'to_minecraft', 'to_discord'], default: 'both' },
        }],
        serverSettings: { type: String, ref: 'ServerSettingsConnections' },
    },
    ServerSettingsConnection: {
        _id: { type: String },
        filteredCommands: [String],
        language: String,
        server: { type: String, ref: 'ServerConnection' },
    },
    UserConnection: {
        _id: { type: String },
        uuid: { type: String, unique: true },
        username: String,
        userSettings: { type: String, ref: 'UserSettingsConnection' },
        customBot: { type: String, ref: 'CustomBotConnection' },
    },
    UserSettingsConnection: {
        _id: { type: String },
        tokens: {
            accessToken: String,
            refreshToken: String,
            expires: Number,
        },
        user: { type: String, ref: 'UserConnection' },
    },
    CustomBotConnection: {
        _id: { type: String },
        port: Number,
        ownerId: String,
        communicationToken: String,
    },
    AnalyticsSnapshot: {
        _id: String,
        timestamp: { type: Date, index: true },
        period: { type: String, enum: ['hourly'], default: 'hourly' },
        guilds: {
            total: Number,
            joined: Number,
            left: Number,
        },
        users: {
            approximate: Number,
        },
        shards: [{
            _id: false,
            id: Number,
            guilds: Number,
            ping: Number,
            uptime: Number,
            memoryMB: Number,
            cpuPercent: Number,
        }],
        commands: [{
            _id: false,
            name: String,
            count: Number,
            errors: Number,
            avgDurationMs: Number,
        }],
        components: [{
            _id: false,
            name: String,
            count: Number,
            errors: Number,
            avgDurationMs: Number,
        }],
        apiCalls: {
            rest: [{
                _id: false,
                name: String,
                count: Number,
                avgDurationMs: Number,
            }],
            ws: [{
                _id: false,
                name: String,
                count: Number,
                errors: Number,
                avgDurationMs: Number,
            }],
        },
        machine: {
            cpuPercent: Number,
            memoryUsedMB: Number,
            memoryTotalMB: Number,
        },
        connections: {
            servers: Number,
            users: Number,
            online: Number,
        },
        chatMonitor: {
            throughput: {
                incoming: Number,
                enqueued: Number,
                processed: Number,
            },
            queue: {
                destinations: Number,
                items: Number,
            },
            rateLimits: {
                type: Map,
                of: Number,
            },
            failures: {
                permission: Number,
                creation: Number,
            },
            operations: [{
                _id: false,
                name: String,
                count: Number,
                rateLimits: Number,
            }],
        },
    },
    AnalyticsError: {
        timestamp: { type: Date, default: Date.now, index: true },
        type: { type: String, enum: ['command', 'component', 'api_rest', 'api_ws', 'unhandled'] },
        name: String,
        guildId: String,
        userId: String,
        shardId: Number,
        error: {
            message: String,
            stack: String,
            code: String,
        },
        context: {
            type: Map,
            of: String,
        },
    },
};