GET http://localhost:11111

###

GET http://localhost:11111/file/get/?hash=hash&path=/path/to/file

###

POST http://localhost:11111/file/put/?hash=hash&path=/path/to/file

< ./command_template.txt

###

GET http://localhost:11111/file/find/?hash=hash&file=level.dat&path=/path/to/file&depth=4

###

GET http://localhost:11111/command/?hash=hash&cmd=tellraw+Lianecx+"The+BOIIISS+are+here!"

###

GET http://localhost:11111/chat/?hash=hash&msg=bruhhhhh&username=Lianecx

###

POST http://localhost:11111/connect/

content-type: application/json

{
    "hash": "hash",
    "chat": false,
    "guild": "844156404477853716",
}

###

POST http://smp.minecraft.to:11111/log/

content-type: application/json

{
    "message": "Ayoo this is for the console"
}