###

GET http://localhost:11111

###

GET http://localhost:11111/file/get/?path=/path/to/file

Authorization: Basic hash

###

POST http://localhost:11111/file/put/?path=/path/to/file

Authorization: Basic hash

< ./command_template.txt

###

GET http://localhost:11111/file/find/?file=level.dat&path=/path/to/file&depth=4

Authorization: Basic hash

###

GET http://localhost:11111/command/?cmd=tellraw+Lianecx+"The+BOIIISS+are+here!"

Authorization: Basic hash

###

GET http://localhost:11111/chat/?msg=bruhhhhh&username=Lianecx

Authorization: Basic hash

###

POST http://localhost:11111/connect/

content-type: application/json
Authorization: Basic code, Basic hash

{
    "chat": false,
    "guild": "844156404477853716"
}

###

GET http://localhost:11111/verify/

###